### ISSUE TITLE
UI Login issues

### ISSUE THREAD

**Issue by jemershaw** [joyent/conch-ui#157]
When navigating [here](https://staging.conch.joyent.us/#/496f76b4-8245-4d41-8d97-42fe988401c5/datacenter/ap-northeast-1a/rack/18a17398-e9f7-4a4c-8234-943da4154a5d/device) there seems to be two different problems but could stem from the same bug.

* If you are logged in:  the session will be killed and you have to navigate to the main login page, refreshing will not redirect you to the login prompt.
* If you are not logged in then you will never reach a login prompt the page will be two spinning wheels(left navigation, and the page information). Same resolution to fix the issue which would be navigating to the root URI.

It seems like there are a bunch of Uncaught in promise errors  which prevents anything from working.

**Comment by karenetheridge** [comment]
I still see this on v3, e.g. at the page https://edge.conch.joyent.us/#/49428a45-b29d-4913-823e-c5569eb8502d/status I see https://www.dropbox.com/s/8pteekvu2uilhl7/Screenshot%202019-10-17%2013.58.09.png?dl=0, and uncaught exceptions in the web console.

**Comment by karenetheridge** [comment]
This still seems to be a problem in v2 -- I went to https://conch.joyent.us/#/60f749b1-c8a0-4f8c-bcb2-e7822a3ff691/datacenter and the page displays "undefined workspace datacenters" with an endless spinner.  Going to a different browser tab and refreshing https://conch.joyent.us/#/ shows that my login session has expired.

**Comment by perigrin** [comment]
It's not that the login session has expired, it seems more like the application initialization that normally happens when you first log in is never completed when you load the sub-URL (which makes some sense) and so the JWT for the login is never stored and other important data (like the workspace) is never populated (although it does make a valid request to /me and gets a response with the data it needs for populating the workspaces).
