### ISSUE TITLE
v2 api: use ?ids_only when fetching large amounts of data

### ISSUE THREAD

**Issue by karenetheridge** [joyent/conch-ui#169]
When fetching all devices in a workspace (for the purpose of listing which can be added to another workspace), please use `?ids_only=1` to reduce the load on the database.

**Comment by dustinryerson** [comment]
Per our discussion over chat, this isn't feasible based on the current design of the Devices page, which utilizes more information than just the `deviceId`.

That being said, the overall usefulness of the Devices page should be reevaluated based on feedback from users, and if it is determined that the page is useful, then a paginated response would most likely be best - that way we can limit the number of devices being requested and displayed on the page, rather than getting a response of over 10k devices and displaying them all on the page at once.

Action items:
- [ ] Get feedback from users about Devices page usefulness
- [ ] Determine a plan of action for updating the page (either redesigning it or removing it completely)
- [ ] Create any necessary GitHub Issues on the `conch` repo for API updates for page redesign

**Comment by dustinryerson** [comment]
I've received feedback from Jeff about the Devices page. He's used it in the past by searching for devices with a device serial number.

It seems like this page is still useful, but it should be redesigned based on the feedback of how it's primarily used. Rather than requesting all existing devices and hammering the DB and browser, it should be easy enough to utilize a search feature which will find devices by serial numbers, asset tags or similar relevant identifiers. The current strain on the DB should be alleviated by completely removing the usage of the `GET /:workspace_id_or_name/device`.

When I have some time, I'll redesign the page and provide more information on how the API usage will change.

**Comment by dustinryerson** [comment]
This issue has been resolved.

**Comment by karenetheridge** [comment]
> This issue has been resolved.

How?

**Comment by dustinryerson** [comment]
> > This issue has been resolved.
> 
> How?

All workspace endpoints have been removed.
